apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.istio.internetIngressLabel }}
  namespace: istio-system
spec:
  selector:
    istio: {{ .Values.istio.internetIngressLabel }}
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.fqdn }}
        # This is a wildcard for all subdomains of dnc.archon.inc
        # but, counterintuitively, it also needs to exist to route
        # some traffic to dnc.archon.inc. This is because the SNIs in the
        # TLS handshake have some attached lookup info like so:

        # [2025-03-19T21:48:10.072Z] "- - -" 0 NR filter_chain_not_found
        # - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.244.1.119:443 10.0.0.7:36646
        # outbound_.443_._.dnc.archon.inc - [[this is from before the wildcard was added]]

        # The SNI is outbound_.443_._.dnc.archon.inc, and is matched below
        # UPDATE: Check the file for workload configuration for more info on SNI setting, as
        # we now manually pin the SNI so this shouldn't be as necessary
        - "*.{{ .Values.fqdn }}"
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.fqdn | quote }}
        