env:
  contexts:
    - name: Keycloak Auth
      urls:
        - "{{ .Env.Z_URL }}"
      includePaths:
        # This injects regex, which needs single quotes
        # prettier-ignore
        - '{{ .Env.Z_URL_REGEX }}.*'
      excludePaths:
        # Ignore any numbered Jenkins jobs (no reason to bother, they are identical to the named ones)
        # This matches URL/job/jenkins-job-name/number or URL/view/view-name/job/jenkins-job-name/number
        - '{{ .Env.Z_URL_REGEX }}\/.*\/execution\/node\/[0-9].*'
        # prettier-ignore
        - '{{ .Env.Z_URL_REGEX }}(/me/my-views)?(/view/[^/]+)?/job/[^/]+/[0-9]+(?:/.*)?'
        - '{{ .Env.Z_URL_REGEX }}(\/me\/my-views)?(\/view\/[^/]+)?\/job\/[^/]+\/[^/]+\/artifact.*'
        - '{{ .Env.Z_URL_REGEX }}\/static\/.*'
        - '{{ .Env.Z_URL_REGEX }}\/fingerprint\/.*'
      authentication:
        method: browser
        parameters:
          loginPageUrl: "{{ .Env.Z_URL }}"
          browserId: firefox-headless
          loginPageWait: 10
          steps:
            - description: auto
              type: AUTO_STEPS
              timeout: 1000
        verification:
          method: poll
          loggedInRegex: \Q 200 OK\E
          loggedOutRegex: \Q 403 Forbidden\E
          pollFrequency: 60
          pollUnits: requests
          pollUrl: "{{ .Env.Z_URL }}/i18n/resourceBundle?baseName=jenkins.dialogs&_=1747303641693"
          pollPostData: ""
      sessionManagement:
        method: headers
      technology: {}
      structure: {}
      users:
        - name: env-user
          credentials:
            password: "{{ .Env.Z_KEYCLOAK_PASS }}"
            username: "{{ .Env.Z_KEYCLOAK_USER }}"
  parameters: {}
jobs:
  - type: passiveScan-config
    parameters:
      scanOnlyInScope: true
  - type: spider
    parameters:
      context: Keycloak Auth
      user: env-user
      url: "{{ .Env.Z_URL }}"
  - type: passiveScan-wait
    parameters:
      maxDuration: 1200
  - type: report
    parameters:
      template: traditional-json
      reportDir: .
      reportTitle: ZAP Report
      reportDescription: ZAP Report
  - type: report
    parameters:
      template: traditional-pdf
      reportDir: .
      reportTitle: ZAP Report
      reportDescription: ZAP Report
