env:
  contexts:
    - name: Authentication Test
      urls:
        - "{{ .Env.Z_URL }}"
      includePaths:
        - "{{ .Env.Z_URL_REGEX }}.*"
      authentication:
        method: browser
        parameters:
          loginPageUrl: "{{ .Env.Z_URL }}"
          browserId: firefox-headless
          loginPageWait: 10
          steps:
            - description: auto
              type: AUTO_STEPS
              timeout: 1000
        verification:
          method: poll
          loggedInRegex: \Q 200 OK\E
          loggedOutRegex: \Q 302 Found\E
          pollFrequency: 60
          pollUnits: requests
          pollUrl: "{{ .Env.Z_URL }}/realms/master/account?referrer=security-admin-console&referrer_uri={{ .Env.Z_URL | urlquery }}%2Fadmin%2Fmaster%2Fconsole%2F"
          pollPostData: ""
      sessionManagement:
        method: headers
        parameters:
          cookie: "KC_AUTH_SESSION_HASH={%cookie:KEYCLOAK_SESSION%}"
      technology: {}
      structure: {}
      users:
        - name: env-user
          credentials:
            password: "{{ .Env.Z_KEYCLOAK_PASS }}"
            username: "{{ .Env.Z_KEYCLOAK_USER }}"
  parameters: {}
options:
  config:
    - name: view.mode
      value: SAFE
jobs:
  - type: spider
    parameters:
      context: Authentication Test
      user: env-user
      parseDsStore: null
  - type: spiderAjax
    parameters:
      context: Authentication Test
      user: env-user
      browserId: firefox-headless
  - type: passiveScan-wait
    parameters:
      maxDuration: 1200
  - type: report
    parameters:
      template: traditional-json
      reportDir: "."
      reportTitle: "ZAP Report"
      reportDescription: "ZAP Report"
  - type: report
    parameters:
      template: traditional-pdf
      reportDir: "."
      reportTitle: "ZAP Report"
      reportDescription: "ZAP Report"
