apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-inbound-and-cross-traffic
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
        "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
        "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
        "app.kubernetes.io/instance": "{{ .Release.Name }}"
        "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/istio-system/sa/ingress-from-internet" # Allow traffic from the gateway
      to:
        - operation:
            ports: ["8080"] # Allow inbound traffic
    - from:
        - source:
            principals:
              - "cluster.local/ns/{{ .Values.agent.namespace }}/sa/jenkins-*"
      to:
        - operation:
            ports: ["50000", "8080"] # Allow worker traffic