apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-inbound-and-cross-traffic
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      app.kubernetes.io/component: keycloak
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/istio-system/sa/ingress-from-internet" # Allow traffic from the gateway
      to:
        - operation:
            ports: ["8080"] # Allow inbound traffic
    - from:
        - source:
            principals:
              - "cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.azureIdentity.name }}" # Allow cross-pod traffic
      to:
        - operation:
            ports: ["7800"] 
