apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-keycloak-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    # NOTE: This actually has to be in here or else Istio will not
    # know to route traffic to the headless service
    # See https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/#headless-services
    - name: discovery
      port: 7800
      protocol: TCP
      targetPort: discovery
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: keycloak