apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.azureIdentity.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azureIdentity.clientId | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/component: keycloak
