apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: database-service-entry
spec:
  hosts:
  - "*.postgres.database.azure.com"
  location: MESH_EXTERNAL
  ports:
  - number: 5432
    name: tcp
    protocol: TCP
  resolution: NONE